### PR TITLE
Fix #[derive(Fail)] when mixing no_std and std crates

### LINKED ISSUE #214: #[derive(Fail)] assumes std exists
This isn't the case for `#[no_std]` libraries. This can be dealt with by making `failure` export an undocumented `core` (something like `#[doc(hidden)] pub use core`). Or it could be documented that an user needs to use `use core as std` in such libraries.

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #214

### CODE REVIEW

**Comment by jonhoo** [comment]
This'll have to be updated now that https://github.com/rust-lang-nursery/failure/pull/228 has landed.

**Comment by Amanieu** [comment]
Rebased

**Comment by jonhoo** [comment]
@mitsuhiko this PR looks like it might be a good candidate before a potential release.

**Comment by mitsuhiko** [comment]
Fixed. Thanks!

**Pull request closed without merging**
