### PR TITLE
Update syn to 0.13, quote to 0.5 and synstructure to 0.8

### PR DESCRIPTION
**Pull request by hcpl**

### CODE REVIEW

**Comment by hcpl** [comment]
Oops, break with value is a 1.19+ feature used in https://github.com/mystor/synstructure/blob/dad0b18ea2ba392db45499dd677f4124f18c5883/src/lib.rs#L2104.

**Comment by hcpl** [comment]
Filed an issue to `synstructure`: https://github.com/mystor/synstructure/issues/14 to clarify the situation around supported Rust versions.

**Comment by hcpl** [comment]
https://github.com/mystor/synstructure/issues/14 has been resolved with `synstructure` 0.8.1 release and tests now pass!

**Comment by withoutboats** [comment]
Thanks! :) sorry it took me so long to review!

**Pull request merged**
