### PR TITLE
Don't duplicate code for small-error

### PR DESCRIPTION
**Pull request by matklad**
So, while implementing #159, I've noticed that I have to duplicate docstrings for small-error. I though that maybe we can get rid of this duplication, by separating the `Error` API (which is the same for both cases) and the implementation (which actually differs). Not sure if it's worth doing this, but at least it seems to work =P

### CODE REVIEW

**Comment by withoutboats** [comment]
Could you nest these inside an `error` directory with submodules for the two impls?

**Comment by matklad** [comment]
Sure!

**Comment by matklad** [comment]
I would have named submodules `impl` and `impl_small`, but `impl` is a keyword 😒

**Comment by withoutboats** [comment]
I rebased and fixed this. :-)

**Pull request closed without merging**
