### PR TITLE
add Context::map

### PR DESCRIPTION
**Pull request by little-dude**
This is similar to other `map` methods in the rust ecosystem
(`Option::map` for instance) and allow turning a `Context<T>` into a
`Context<U>`

This makes it easier to implement custom error types that can be
chained. Consider for instance the following error:

```rust
use core::fmt::{self, Display};
use failure::{Backtrace, Context, Fail, ResultExt};

pub struct MyError {
    inner: Context<String>,
}

impl From<&'static str> for MyError {
    fn from(msg: &'static str) -> MyError {
        MyError {
            inner: Context::new(msg.into()),
        }
    }
}

impl Fail for MyError {
    fn cause(&self) -> Option<&Fail> {
        self.inner.cause()
    }

    fn backtrace(&self) -> Option<&Backtrace> {
        self.inner.backtrace()
    }
}

impl Display for MyError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Display::fmt(&self.inner, f)
    }
}
```

We can make it easy to chain such errors with a `Context<String>`:

```rust
impl From<Context<String>> for MyError {
    fn from(inner: Context<String>) -> MyError {
        MyError { inner }
    }
}
```

Now we can do:

```rust
fn main() {
    println!("{:?}", err2());
}

fn err1() -> Result<(), MyError> {
    Ok(Err(MyError::from("err1"))?)
}

fn err2() -> Result<(), MyError> {
    // chaining works correctly
    Ok(err1().context("err2".to_string()))
}
```

However, without `map` it's impossible to chain such errors with a
`Context<&'static str>`. With `map` however:

```rust
impl From<Context<&'static str>> for MyError {
    fn from(inner: Context<&'static str>) -> MyError {
        MyError {
            inner: inner.map(|s| s.to_string()),
        }
    }
}
```

And we can now do:

```rust
fn main() {
    println!("{:?}", err2());
}

fn err1() -> Result<(), MyError> {
    Ok(Err(MyError::from("err1"))?)
}

fn err2() -> Result<(), MyError> {
    // chaining works correctly
    Ok(err1().context("err2"))
}
```

Ref: https://github.com/rust-lang-nursery/failure/issues/259

### CODE REVIEW

**Comment by little-dude** [comment]
@mitsuhiko what's your opinion about this change? I don't want to start using this if there's no chance for this PR to be accepted.

**Comment by yoshuawuyts** [comment]
I really like the functionality this change provides. If I'm understanding this correctly it would allow us to write meaningful error messages, and then wrap them in an `ErrorKind` / `Error` pair so that we can distinguish between different error types.

Given that's all true I'm _super_ stoked for this change!

**Comment by little-dude** [comment]
@yoshuawuyts I think what you describe is already possible, it's the workflow described in the [chapter 3.4 of the failure book](https://boats.gitlab.io/failure/error-errorkind.html) no?

I think what this provides is a variation of the workflow described in the [chapter 3.3 (Using The Error Type)](https://boats.gitlab.io/failure/use-error.html). Instead of using failure's `Error` type, you can define your own and use it the same way.

But I'm pretty new to failure (I'm trying to use it for the first time), so I may be wrong.

**Comment by yoshuawuyts** [comment]
@little-dude so wrapping around errors currently works fine:
```rust
perform_some_io().context(ErrorKind::NetworkFailure)?;
```
`io` created an error, and we're providing more context to it by calling it "NetworkFailure".

But if we have a custom error of sorts, this type of error wrapping becomes a bit tedious. After all: we now need to create a new error kind for each type of failure. Instead it would be much easier if we could do:

```rust
Err(MyError::from("err1"))
```

Which creates a new error of type `MyError`, and a custom error message. Although now that I'm typing this out, I'm wondering if it shouldn't be implemented on `ErrorKind` instead, so we can have a function like:

```rust
fn foo -> MyError {
  Err(ErrorKind::Something::from("oh no!")
}
```
I guess this probably warrants an issue by itself actually.

**Comment by little-dude** [comment]
```rust
fn foo -> MyError {
  Err(ErrorKind::Something::from("oh no!")
}
```

Did you mean `ErrorKind::from("oh no!")` ? I think you can already do that.

**Comment by little-dude** [comment]
09c11eb is unrelated to the `Context::map` changes, but since it was tiny I put it in the PR, but let me know if you'd rather have a different PR.

**Comment by mitsuhiko** [comment]
@little-dude i'm fine with it being in the same PR because I do plan on pulling this in.

**Comment by little-dude** [comment]
Sounds good. I'm not sure what test to add and where. There is no test in `src/context.rs` or in `src/lib.rs`. Does the example count as a test?

**Comment by mitsuhiko** [comment]
@little-dude i know there are not enough tests. I would add one to `src/context.rs` at the bottom. The library is light on tests at the moment but we should not continue this bad precedent.

**Comment by little-dude** [comment]
Sure, I'll add tests tonight then.

**Comment by little-dude** [comment]
@mitsuhiko I think the book needs to be updated.

**Pull request merged**
